### PR TITLE
pr: run tests

### PR DESCRIPTION
**Pull request by shashanksinha89**
- Run test cases
- NPM package publish

### CODE REVIEW

**Comment by angle943** [comment]
@shashanksinha89 hmm any idea why some tests are failing/canceled?

**Comment by shashanksinha89** [comment]
> @shashanksinha89 hmm any idea why some tests are failing/canceled?

installed missing dependencies.

**Comment by angle943** [comment]
@shashanksinha89 can you resolve the merge conflicts please? Thanks in advance!

**Comment by shashanksinha89** [comment]
> @shashanksinha89 can you resolve the merge conflicts please? Thanks in advance!

fixed.

**Pull request merged**
